// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// This file contains Firebase configuration options for different platforms.
// It was automatically generated by the FlutterFire CLI tool.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class provides platform-specific Firebase configuration settings.
/// The app automatically selects the correct configuration based on the
/// platform it's running on (web, Android, iOS, macOS, Windows).
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the Firebase configuration for the current platform.
  ///
  /// This getter automatically detects which platform the app is running on
  /// and returns the appropriate Firebase configuration options.
  static FirebaseOptions get currentPlatform {
    // Check if running on web platform
    if (kIsWeb) {
      return web;
    }
    
    // For non-web platforms, determine the specific platform
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration options for Web platform.
  ///
  /// Contains essential Firebase credentials for web applications:
  /// - apiKey: Used for authentication
  /// - appId: Unique identifier for this Firebase app
  /// - messagingSenderId: Used for Firebase Cloud Messaging
  /// - projectId: The Firebase project ID
  /// - authDomain: Domain for Firebase Authentication
  /// - storageBucket: Storage location for Firebase Storage
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2WZtbsN34wfDEpHvGA0yEjW6m3pAo1ak',
    appId: '1:520338240107:web:5468826b6c48c5d8c8372e',
    messagingSenderId: '520338240107',
    projectId: 'swift-d03e5',
    authDomain: 'swift-d03e5.firebaseapp.com',
    storageBucket: 'swift-d03e5.firebasestorage.app',
  );

  /// Firebase configuration options for Android platform.
  ///
  /// Contains Android-specific Firebase credentials:
  /// - apiKey: Used for authentication (Android-specific)
  /// - appId: Unique identifier for this Firebase app on Android
  /// - messagingSenderId: Used for Firebase Cloud Messaging
  /// - projectId: The Firebase project ID
  /// - storageBucket: Storage location for Firebase Storage
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrtb-LFfvEpjcIgsO4hxi0rBlVmb0pSM',
    appId: '1:520338240107:android:6ad3ff562b218162c8372e',
    messagingSenderId: '520338240107',
    projectId: 'swift-d03e5',
    storageBucket: 'swift-d03e5.firebasestorage.app',
  );

  /// Firebase configuration options for iOS platform.
  ///
  /// Contains iOS-specific Firebase credentials:
  /// - apiKey: Used for authentication (iOS-specific)
  /// - appId: Unique identifier for this Firebase app on iOS
  /// - messagingSenderId: Used for Firebase Cloud Messaging
  /// - projectId: The Firebase project ID
  /// - storageBucket: Storage location for Firebase Storage
  /// - iosBundleId: The bundle identifier for the iOS app
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf9zxJ0g1x3xxr04GgKgCxiUydsBXj2ro',
    appId: '1:520338240107:ios:e4dfdca816e14c4ec8372e',
    messagingSenderId: '520338240107',
    projectId: 'swift-d03e5',
    storageBucket: 'swift-d03e5.firebasestorage.app',
    iosBundleId: 'com.example.shiftApplication',
  );

  /// Firebase configuration options for macOS platform.
  ///
  /// Contains macOS-specific Firebase credentials:
  /// - apiKey: Used for authentication (same as iOS in this case)
  /// - appId: Unique identifier for this Firebase app on macOS
  /// - messagingSenderId: Used for Firebase Cloud Messaging
  /// - projectId: The Firebase project ID
  /// - storageBucket: Storage location for Firebase Storage
  /// - iosBundleId: The bundle identifier for the macOS app
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf9zxJ0g1x3xxr04GgKgCxiUydsBXj2ro',
    appId: '1:520338240107:ios:e4dfdca816e14c4ec8372e',
    messagingSenderId: '520338240107',
    projectId: 'swift-d03e5',
    storageBucket: 'swift-d03e5.firebasestorage.app',
    iosBundleId: 'com.example.shiftApplication',
  );

  /// Firebase configuration options for Windows platform.
  ///
  /// Contains Windows-specific Firebase credentials:
  /// - apiKey: Used for authentication (same as web in this case)
  /// - appId: Unique identifier for this Firebase app on Windows
  /// - messagingSenderId: Used for Firebase Cloud Messaging
  /// - projectId: The Firebase project ID
  /// - authDomain: Domain for Firebase Authentication
  /// - storageBucket: Storage location for Firebase Storage
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2WZtbsN34wfDEpHvGA0yEjW6m3pAo1ak',
    appId: '1:520338240107:web:54d5eb9b36ca2a68c8372e',
    messagingSenderId: '520338240107',
    projectId: 'swift-d03e5',
    authDomain: 'swift-d03e5.firebaseapp.com',
    storageBucket: 'swift-d03e5.firebasestorage.app',
  );
}
